steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - container
      - clusters
      - get-credentials
      - eng-shared-7-2
      - '--region=us-east1'
    id: authenticate
    waitFor:
      - '-'
  - name: 'us-docker.pkg.dev/$PROJECT_ID/images/skaffold:latest'
    args:
      - '-c'
      - ./bin/forgeops delete -n $$NAMESPACE --yes --force
    id: nuke-environment
    waitFor:
      - authenticate
    entrypoint: bash
  - name: 'us-docker.pkg.dev/$PROJECT_ID/images/skaffold:latest'
    args:
      - '-c'
      - ./bin/forgeops install --fqdn nightly.eng72.forgeops.com -n $$NAMESPACE
    id: deploy-cdk
    waitFor:
      - nuke-environment
    entrypoint: bash
  - name: 'us-docker.pkg.dev/$PROJECT_ID/images/skaffold:latest'
    args:
      - '-c'
      - ./cicd/bin/smoke-tests
    id: smoke-tests
    waitFor:
      - deploy-cdk
    entrypoint: bash
  - name: 'us-docker.pkg.dev/$PROJECT_ID/images/skaffold:latest'
    args:
      - '-c'
      - ./cicd/bin/nightly-slack-notify release/7.2.0
    id: slack-notify
    waitFor:
      - smoke-tests
    entrypoint: bash
    secretEnv:
      - SLACK_WEBHOOK_URL
      - SLACK_FAILED_WEBHOOK_URL
timeout: 900s
options:
  env:
    - NAMESPACE=nightly
    - DEFAULT_DOCKER_REPO=us-docker.pkg.dev/engineering-devops/images/nightly-72
    - SET_IMAGES_LOG=/workspace/set_log.txt
availableSecrets:
  secretManager:
    - versionName: >-
        projects/$PROJECT_NUMBER/secrets/slack_webhook_url_nightly/versions/latest
      env: SLACK_WEBHOOK_URL
    - versionName: >-
        projects/$PROJECT_NUMBER/secrets/slack_webhook_url_nightly_team/versions/latest
      env: SLACK_FAILED_WEBHOOK_URL
