kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: forgerock-restricted
readOnlyRootFilesystem: false
allowHostIPC: false
allowHostPID: false
allowHostNetwork: false
allowHostPorts: false
allowHostDirVolumePlugin: false
allowPrivilegedContainer: false
priority: 10
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- default
- system:serviceaccount:secret-agent-system:secret-agent-controller-manager
- system:serviceaccount:fr-system:default
- system:serviceaccount:forgerockopenshift:default

volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
