apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkZWZhdWx0LXJvdXRlLW9wZW5zaGlmdC1pbWFnZS1yZWdpc3RyeS5hcHBzLWNyYy50ZXN0aW5nIjogewoJCQkiYXV0aCI6ICJhM1ZpWldGa2JXbHVPalpmU1ZZdFZWbFNkR3RVU3pkdmFrRnFSMlpmVmxGQmVsZzRaelYyTldwNU4xbFFTMkpuYmtOR1ZEQT0iCgkJfSwKCQkiZGVmYXVsdC1yb3V0ZS1vcGVuc2hpZnQtaW1hZ2UtcmVnaXN0cnkuYXBwcy5zbm8uYm9zYS5iZWxnaXVtLmJlIjogewoJCQkiYXV0aCI6ICJiV0YyWkRwemFHRXlOVForTlU5U2QySTRlRkp4Tm1kSE9VdE5abEEzTm14TlZYTkRVRGR1VjB4c1VVbGpVSGhLVERSemIwTmhWUT09IgoJCX0sCgkJImRlZmF1bHQtcm91dGUtb3BlbnNoaWZ0LWltYWdlLXJlZ2lzdHJ5LmFwcHMuc25vLmJvc2EuYmVsZ2l1bS5iZTo0NDMiOiB7CgkJCSJhdXRoIjogImJXRjJaRG80VXkxRFpGTXlhbE10VTJaeGNGY3lVRTlCVVRaWVJHMWZSR1kzTUROcmMwNTVPVmxGWjFNMFpYQmoiCgkJfSwKCQkicmVnaXN0cnktZnNmLnNlcnZpY2VzLmJlbGdpdW0uYmU6NTAwMCI6IHsKCQkJImF1dGgiOiAiYldGNGFXMHVkbUZ1WkdWaWNtOWxZMnM2TWpCWmVXRk1SSGhxVm05VFZHaHhZVTh5WlcwPSIKCQl9Cgl9Cn0=
kind: Secret
metadata:
  name: gitlabpullsecret
type: kubernetes.io/dockerconfigjson
