steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/skaffold'
    - '-t'
    - 'us-docker.pkg.dev/$PROJECT_ID/images/skaffold'
    - '-f'
    - 'cicd/skaffold/Dockerfile'
    - 'cicd/skaffold'
images:
  - 'gcr.io/$PROJECT_ID/skaffold'
  - 'us-docker.pkg.dev/$PROJECT_ID/images/skaffold'
