#Patch DS CTS
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds-cts
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ds
          resources:
            requests:
              memory: 1Gi
              cpu: 1000m
            limits:
              memory: 1Gi
      initContainers:
      - name: initialize
        resources:
          requests:
            memory: 1Gi
            cpu: 1000m
          limits:
            memory: 1Gi
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        pv.beta.kubernetes.io/gid: "0"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
      storageClassName: fast